# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98014d0893b69e68a9ae20f76fc4fac227869907062fdb47fff7d3747f8f389300a66e520138047ea4cbf585aee3e562c908e76095e0a1e2530bcdf6cd5d8f65

test:
  secret_key_base: 2595be27ccc12b57f3744602f1d71a62073225793073e53b8568a1a538f4724714e318b27d440c8f554a07a48c4916ecead553f2d173348fca0e25a733989271

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
